name: Flutter android build
on:
  push:
      branches:
        - test
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.0.x
      - run: flutter pub get
      - run: flutter build apk --debug --split-per-abi
      - run: flutter build ios --release
      - run: flutter build web